[package]
name = "timesync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps = "0.1.1"
chrono = "0.4"
num-traits = "0.2.14"

[build-dependencies]
sixtyfps-build = "0.1"
